### ISSUE TITLE
Setup section: final checklist

### ISSUE THREAD

**Issue by ngurenyaga** [MasterFacilityList/mfl_admin_web#21]
Setup screens for:

 - [ ] Contact types
 - [ ] Towns
 - [ ] Counties and county boundaries ( display embedded map )
 - [ ] Constituencies and constituency boundaries ( display embedded map )
 - [ ] Wards and ward boundaries ( display embedded map )
 - [ ] Owners and owner types ( display embedded map )
 - [ ] Job titles
 - [ ] Regulating bodies and regulating body contacts
 - [ ] Community health unit statuses
 - [ ] Community health unit approvers
 - [x] Communities ( for CHUL )
