### ISSUE TITLE
Admin section: final checklist

### ISSUE THREAD

**Issue by ngurenyaga** [MasterFacilityList/mfl_admin_web#22]
- [ ] Linking users and groups
 - [ ] Linking users to contacts
 - [ ] Roadblock on first login or after password reset
