### ISSUE TITLE
Facility workflows: final checklist

### ISSUE THREAD

**Issue by ngurenyaga** [MasterFacilityList/mfl_admin_web#24]
- [ ] Facilities, addresses, contacts, units and services ( consolidated workflow, not five separate screens; the facility detail view should have a header that summarizes pertinent information e.g code, status, regulatory information etc )
- [ ] Publishing workflow
- [ ] Approval ( maker-checker; SCHRIO / CHRIO )
- [ ] Regulation workflow
- [ ] Upgrade workflow
- [ ] Downgrade workflow
- [ ] Facility detail report ( shared with public front-end )
- [ ] Ratings report
- [ ] Facility correction template
- [ ] Cover letter
