### ISSUE TITLE
Dashboard: final checklist

### ISSUE THREAD

**Issue by ngurenyaga** [MasterFacilityList/mfl_admin_web#25]
- [ ] Analysis of facilities by administrative unit
- [ ] Analysis of facilities by type
- [ ] Analysis of facilities by owner / owner type
- [ ] Analysis of facilities by regulator / regulatory status
