### ISSUE TITLE
June 2nd Review Checklist

### ISSUE THREAD

**Issue by bmarika** [MasterFacilityList/mfl_admin_web#65]
@jason-wanjohi 
-  [x] Ensure there is fallback plan for old/unsupported browsers
    - [x] Have logos for the 4 main browsers.
    - [x] The logos should link to a browser's official download pages
- [ ] Make sure search works everywhere

@owagaantony 
- [x] Add year to copyright information
- [ ] Fix page titles
- [x] Fix header: should show user
- [x] Remove top nav icons
- [x] Rename "CHUs" to "Community Units"
- [ ] Implement user profile
- [x] The forms that are inside cards should have more padding
- [x] Change order of menu entries in the services section ( categories come first )
- [ ] When you are in a nested view e.g "Add a service category", the relevant entry in the side nav should be highlighted
- [ ] Review action buttons for all forms e.g Delete makes no sense for a new item
- [ ] Handle HTTP 429 for rating API
- [ ] Finalize on navigation
    - [ ] Add all the links that should be part of the navigation bar
    - [ ] Think through drop-downs
    - [ ] Add the default url
- [x] Fix login page:
  - [x] Replace "username" with "email"
  - [x] Fix the login button
- [x] Site name(Master Facility List V2.0) should link back to the home page
- [ ] For all dropdowns, the front-end should explicitly request sorting by name, ascending order. Extend this to the public front-end.
- [x] Fix "Cancel" in forms
- [ ] Create a default error 404 page
- [ ] Fix the dashboard
    - [x]  Styling
    - [x] Have better names for the panel titles
    - [x] Fix county level user; Constituencies do not show
    - [ ] Fix the state of the dashboard when a user is not logged 
- [ ] Add a notification area 
- [ ] Typo in footer (period & space)
- [ ] In Top 20 counties hover should show details of that particular county
- [ ] Bar chart titles should be in title case
- [ ] Normalize chart legends(should all be in sentence case)
- [ ] Facilities navigation should highlight properly
- [ ] Page titles should be uniform
- [ ] Turn off CHU

@liyocee 
- [ ] Implement Community Health Units (CHU)
    - [ ]  Implement CHU CRUD
        - [ ] Ensure a CHU has contacts
        - [ ] Ensure a CHU has approvals
    - [ ] Implement (Community Health Extension worker)CHEW CRUD
        - [ ] Ensure a CHEW has contacts
        - [ ] Ensure a CHEW has approvals
- [ ] Implement a combo box, replace all voluminous selects with it
- [ ] Style the service catalog
- [ ] Implemment the admin(Setup ) section of the admin
    - [ ] Have all setup data CRUD implemented
        - [ ] Contact types
        - [ ] Towns
        - [ ] Counties
        - [ ] Constituencies
        - [ ] Wards
        - [ ] Owners and owner types 
        - [ ] Job titles
        - [ ] Regulating bodies and regulating body contacts
        - [ ] Community health unit statuses
        - [ ] Community health unit approvers
        - [ ] show admin units codes. (Remove auto-numbers)

- [ ] Sorting in select, combo box (Stupid)
- [ ] Grid search 
- [ ] Excel export
- [ ] Facilities get basics in

@ngash 
 - [ ] User management
       - [ ] User CRUD
       - [ ] User contacts
       - [ ] User groups
       - [ ] User Counties
       - [ ] Roadblock on login after password reset
- [ ] Every drop down should handle pagination
- [ ] Dashboard redirect
- [ ] Lock access to the application, user must log in
- [ ] Improvised RBAC

**Comment by ngurenyaga** [comment]
Minor formatting improvements needed for @ngash 's section of the checklist.

On Tue, Jun 2, 2015 at 2:15 PM, Brian Marika <notifications@github.com>
wrote:

> @jason-wanjohi <https://github.com/jason-wanjohi>
>
>    -  Ensure there is fallback plan for old/unsupported browsers
>       -  Have logos for the 4 main browsers.
>       -  The logos should link to a browser's official download page
>
> @owagaantony <https://github.com/owagaantony>
>
>    -  Add year to copyright information
>    -  Implement user profile
>    -
>
>    Finalize on navigation
>     -  Add all the links that should be part of the navigation bar
>       -  Think through drop-downs
>     -
>
>    Site name(Master Facility List V2.0) should link back to the home page
>    -  Create a default error 404 page
>    -  Fix the dashboard
>       -  Styling
>       -  Have better names for the panel titles
>       -  Fix county level user; Constituencies do not show
>
> @liyocee <https://github.com/liyocee>
>
>    -
>
>    Implement Community Health Units (CHU)
>     -  Implement CHU CRUD
>          -  Ensure a CHU has contacts
>          -  Ensure a CHU has approvals
>        -  Implement (Community Health Extension worker)CHEW CRUD
>          -  Ensure a CHEW has contacts
>          -  Ensure a CHEW has approvals
>         -
>
>    Style the service catalog
>    -  Implemment the admin(Setup ) section of the admin
>       -  Have all setup data CRUD implemented
>          -  Contact types
>          -  Towns
>          -  Counties
>          -  Constituencies
>          -  Wards
>          -  Owners and owner types
>          -  Job titles
>          -  Regulating bodies and regulating body contacts
>          -  Community health unit statuses
>          -  Community health unit approvers
>
> @ngash <https://github.com/ngash>
> - [ ] Implement User management
> - [ ] User primary details
> - [ ] User contacts
> - [ ] User groups
> - [ ] User Counties
> - [ ] Roadblock on login after password reset
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MasterFacilityList/mfl_admin_web/issues/65>.
>



-- 
Founder & CTO,
Savannah Informatics Limited

No. 11A, off Kabarnet Road

Cellphone: +254-723-002959

ngure.nyaga@savannahinformatics.com
@ngurenyaga

**Comment by bmarika** [comment]
@ngurenyaga I have fixed the formatting
